services:
  server:
    build:
      context: .
      target: dev
    environment:
      DATABASE_URL: mysql://root:root@db:3306/f1
    ports:
      - 4321:4321
    volumes:
      - ./src:/usr/src/app/src
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
